### ISSUE TITLE
Plans for the provider?

### ISSUE THREAD

**Issue by ksatirli** [contentful-labs/terraform-contentful#13]
Hello @tolgaakyuz, @lneves75 and @danihodovic!

I came across this provider after doing a search for ways to better interact with the Contentful API. We're using Terraform internally, so this provider is most welcome!

There haven't been a lot of changes for a while so I was wondering: can you share some thoughts on the future of this provider? 

Specifically, I'm wondering if there's more extensive support for Content Types planned? (The README lists Content Types as "to do", while https://github.com/contentful-labs/terraform-contentful/pull/12 shows it as merged).

Thanks!

**Comment by tolgaakyuz** [comment]
Hey @ksatirli 

Thanks for your interest of this plugin. You are right. Since we are not using this plugin directly here at Contentful, we have kinda abandoned the development for a while.

You can always open an issue for your questions and suggestions. However, since this plugin is not our main priority as of now, we can't guarantee the fixes/improvements to be delivered as quickly as you might be expecting. We will definitely do our best but if you want faster response, PR(s) are the way to go 😉 

Other than that, I will try to update the readme with a possible road map, soonish.

Again, thanks
Cheers 👋

**Comment by danihodovic** [comment]
Hi @ksatirli,

> There haven't been a lot of changes for a while so I was wondering: can you share some thoughts on the future of this provider?

We hacked this together when Contentful allowed us to spend time on a hobby project. The plan was to get it merged to the Terraform core project, but that idea was abandoned with Terraform 0.10 (https://www.terraform.io/upgrade-guides/0-10.html#separated-provider-plugins).

I'm not maintaining this project anymore, but @tolgaakyuz or @lneves75 might be.

> Specifically, I'm wondering if there's more extensive support for Content Types planned? (The README lists Content Types as "to do", while #12 shows it as merged).

Content Types should be supported, however I don't think all of the features are built in to the plugin (e.g fields validations on plugin level).

https://github.com/contentful-labs/terraform-contentful/blob/master/provider.go#L30
https://github.com/contentful-labs/terraform-contentful/blob/master/resource_contentful_contenttype.go#L8

**Comment by willm** [comment]
Just going to bring this up here. We would love to be able to add contentful to other services we manage via terraform. Would love to see this project get a bit of love and published as a provider.

**Comment by danihodovic** [comment]
Hi Will. Three years later and none of the three original authors (me, @minimalog , @lneves75 ) work for Contentful anymore. Your best bet is to ping @elblivion or @Khaledgarbaya.

**Comment by joelmiles** [comment]
@elblivion or @Khaledgarbaya, any news to share on the future of this project?  We'd love to use this if it were brought up-to-date.  Is there a roadmap you can share?
